"""Initial migration

Revision ID: 114ecb0fef06
Revises:
Create Date: 2026-02-27 03:44:14.291506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '114ecb0fef06'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #
    # Note: analyses and artefacts have a circular FK relationship:
    #   analyses.artefact_id -> artefacts.id
    #   artefacts.derived_from_analysis_id -> analyses.id
    #
    # To avoid a dependency cycle we:
    #   1. create artefacts WITHOUT the derived_from_analysis_id FK
    #   2. create analyses (can now reference artefacts)
    #   3. add the deferred FK from artefacts -> analyses
    #
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_name'), ['name'], unique=True)

    op.create_table('external_systems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('system_type', sa.String(length=50), nullable=True),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('url_template', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('external_systems', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_external_systems_name'), ['name'], unique=True)

    op.create_table('platforms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['platforms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('platforms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_platforms_name'), ['name'], unique=True)

    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tags_name'), ['name'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=72), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('hash_databases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('platform_id', sa.Integer(), nullable=True),
    sa.Column('file_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hash_databases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hash_databases_name'), ['name'], unique=True)

    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('platform_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_items_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_platform_id'), ['platform_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_uuid'), ['uuid'], unique=True)

    # Create artefacts WITHOUT the derived_from_analysis_id FK (analyses doesn't exist yet).
    op.create_table('artefacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=32), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('artefact_type', sa.Enum('SCP', 'IMD', 'HFE', 'RAW_SECTOR', 'ISO', 'DD_ZST', 'DD_GZ', 'DD_BZ2', 'PDF', 'ZIP', 'TARGZ', 'RAR', 'UNKNOWN', name='artefacttype'), nullable=False),
    sa.Column('type_overridden', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('storage_directory', sa.Enum('UPLOADS', 'OUTPUTS', name='storagedirectory'), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('md5', sa.String(length=32), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('media_metadata', sa.Text(), nullable=True),
    sa.Column('parent_artefact_id', sa.Integer(), nullable=True),
    sa.Column('derived_from_analysis_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['parent_artefact_id'], ['artefacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artefacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artefacts_derived_from_analysis_id'), ['derived_from_analysis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_artefacts_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_artefacts_parent_artefact_id'), ['parent_artefact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_artefacts_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_artefacts_uuid'), ['uuid'], unique=True)

    # Now create analyses - artefacts exists so the FK is valid.
    op.create_table('analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=32), nullable=False),
    sa.Column('artefact_id', sa.Integer(), nullable=False),
    sa.Column('analysis_type', sa.Enum('FLUX_VISUALISATION', 'FLUX_DECODE', 'SECTOR_DUMP', 'FILE_EXTRACTION', 'ARCHIVE_DETECT', 'ARCHIVE_EXTRACT', 'METADATA_EXTRACT', 'PARTITION_DETECT', 'CHECKSUM_COMPUTE', 'FORMAT_IDENTIFY', name='analysistype'), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='analysisstatus'), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=True),
    sa.Column('tool_version', sa.String(length=50), nullable=True),
    sa.Column('hints', sa.Text(), nullable=True),
    sa.Column('output_url', sa.String(length=500), nullable=True),
    sa.Column('output_path', sa.String(length=1000), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['artefact_id'], ['artefacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analyses_artefact_id'), ['artefact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyses_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyses_uuid'), ['uuid'], unique=True)

    # Add the deferred FK now that both tables exist.
    op.create_foreign_key(
        'fk_artefacts_derived_from_analysis',
        'artefacts', 'analyses',
        ['derived_from_analysis_id'], ['id']
    )

    op.create_table('partitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=32), nullable=False),
    sa.Column('artefact_id', sa.Integer(), nullable=False),
    sa.Column('partition_index', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('filesystem', sa.Enum('FAT12', 'FAT16', 'FAT32', 'NTFS', 'HPFS', 'HFS', 'HFS_PLUS', 'ADFS', 'DFS', 'AMIGA_OFS', 'AMIGA_FFS', 'ISO9660', 'CDFS', 'CPM', 'UNKNOWN', 'OTHER', name='filesystemtype'), nullable=False),
    sa.Column('container_format', sa.Text(), nullable=True),
    sa.Column('start_sector', sa.BigInteger(), nullable=True),
    sa.Column('sector_count', sa.BigInteger(), nullable=True),
    sa.Column('block_size', sa.Integer(), nullable=True),
    sa.Column('total_files', sa.Integer(), nullable=True),
    sa.Column('total_directories', sa.Integer(), nullable=True),
    sa.Column('total_bytes', sa.BigInteger(), nullable=True),
    sa.Column('unique_files', sa.Integer(), nullable=True),
    sa.Column('detection_details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artefact_id'], ['artefacts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artefact_id', 'partition_index', name='uq_partition_artefact_index')
    )
    with op.batch_alter_table('partitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partitions_artefact_id'), ['artefact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_partitions_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_partitions_uuid'), ['uuid'], unique=True)

    op.create_table('external_references',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('external_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['system_id'], ['external_systems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('external_references', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_external_references_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_external_references_item_id'), ['item_id'], unique=False)
        batch_op.create_index('ix_external_references_system_external', ['system_id', 'external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_external_references_system_id'), ['system_id'], unique=False)

    op.create_table('item_tags',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('item_id', 'tag_id')
    )
    op.create_table('known_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('database_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('md5', sa.String(length=32), nullable=True),
    sa.Column('sha1', sa.String(length=40), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('crc32', sa.String(length=8), nullable=True),
    sa.Column('product_name', sa.String(length=200), nullable=True),
    sa.Column('product_version', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['database_id'], ['hash_databases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('known_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_known_files_database_id'), ['database_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_known_files_filename'), ['filename'], unique=False)
        batch_op.create_index(batch_op.f('ix_known_files_md5'), ['md5'], unique=False)
        batch_op.create_index('ix_known_files_md5_size', ['md5', 'file_size'], unique=False)
        batch_op.create_index(batch_op.f('ix_known_files_sha1'), ['sha1'], unique=False)
        batch_op.create_index('ix_known_files_sha1_size', ['sha1', 'file_size'], unique=False)

    op.create_table('extracted_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=32), nullable=False),
    sa.Column('partition_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=1000), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('extension', sa.String(length=20), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('modified_time', sa.DateTime(), nullable=True),
    sa.Column('accessed_time', sa.DateTime(), nullable=True),
    sa.Column('attributes', sa.String(length=50), nullable=True),
    sa.Column('md5', sa.String(length=32), nullable=True),
    sa.Column('sha1', sa.String(length=40), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('crc32', sa.String(length=8), nullable=True),
    sa.Column('known_file_id', sa.Integer(), nullable=True),
    sa.Column('is_known', sa.Boolean(), nullable=False),
    sa.Column('parent_file_id', sa.Integer(), nullable=True),
    sa.Column('is_archive', sa.Boolean(), nullable=False),
    sa.Column('is_directory', sa.Boolean(), nullable=False),
    sa.Column('archive_format', sa.String(length=50), nullable=True),
    sa.Column('risc_os_filetype', sa.String(length=3), nullable=True),
    sa.Column('extraction_depth', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['known_file_id'], ['known_files.id'], ),
    sa.ForeignKeyConstraint(['parent_file_id'], ['extracted_files.id'], ),
    sa.ForeignKeyConstraint(['partition_id'], ['partitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('extracted_files', schema=None) as batch_op:
        batch_op.create_index('ix_extracted_files_archive', ['is_archive', 'risc_os_filetype'], unique=False)
        batch_op.create_index(batch_op.f('ix_extracted_files_extension'), ['extension'], unique=False)
        batch_op.create_index(batch_op.f('ix_extracted_files_filename'), ['filename'], unique=False)
        batch_op.create_index(batch_op.f('ix_extracted_files_is_archive'), ['is_archive'], unique=False)
        batch_op.create_index(batch_op.f('ix_extracted_files_is_directory'), ['is_directory'], unique=False)
        batch_op.create_index(batch_op.f('ix_extracted_files_is_known'), ['is_known'], unique=False)
        batch_op.create_index(batch_op.f('ix_extracted_files_known_file_id'), ['known_file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_extracted_files_md5'), ['md5'], unique=False)
        batch_op.create_index('ix_extracted_files_parent', ['parent_file_id', 'extraction_depth'], unique=False)
        batch_op.create_index(batch_op.f('ix_extracted_files_parent_file_id'), ['parent_file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_extracted_files_partition_id'), ['partition_id'], unique=False)
        batch_op.create_index('ix_extracted_files_partition_known', ['partition_id', 'is_known'], unique=False)
        batch_op.create_index(batch_op.f('ix_extracted_files_risc_os_filetype'), ['risc_os_filetype'], unique=False)
        batch_op.create_index(batch_op.f('ix_extracted_files_sha1'), ['sha1'], unique=False)
        batch_op.create_index(batch_op.f('ix_extracted_files_uuid'), ['uuid'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extracted_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extracted_files_uuid'))
        batch_op.drop_index(batch_op.f('ix_extracted_files_sha1'))
        batch_op.drop_index(batch_op.f('ix_extracted_files_risc_os_filetype'))
        batch_op.drop_index('ix_extracted_files_partition_known')
        batch_op.drop_index(batch_op.f('ix_extracted_files_partition_id'))
        batch_op.drop_index(batch_op.f('ix_extracted_files_parent_file_id'))
        batch_op.drop_index('ix_extracted_files_parent')
        batch_op.drop_index(batch_op.f('ix_extracted_files_md5'))
        batch_op.drop_index(batch_op.f('ix_extracted_files_known_file_id'))
        batch_op.drop_index(batch_op.f('ix_extracted_files_is_known'))
        batch_op.drop_index(batch_op.f('ix_extracted_files_is_directory'))
        batch_op.drop_index(batch_op.f('ix_extracted_files_is_archive'))
        batch_op.drop_index(batch_op.f('ix_extracted_files_filename'))
        batch_op.drop_index(batch_op.f('ix_extracted_files_extension'))
        batch_op.drop_index('ix_extracted_files_archive')

    op.drop_table('extracted_files')
    with op.batch_alter_table('known_files', schema=None) as batch_op:
        batch_op.drop_index('ix_known_files_sha1_size')
        batch_op.drop_index(batch_op.f('ix_known_files_sha1'))
        batch_op.drop_index('ix_known_files_md5_size')
        batch_op.drop_index(batch_op.f('ix_known_files_md5'))
        batch_op.drop_index(batch_op.f('ix_known_files_filename'))
        batch_op.drop_index(batch_op.f('ix_known_files_database_id'))

    op.drop_table('known_files')
    op.drop_table('item_tags')
    with op.batch_alter_table('external_references', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_external_references_system_id'))
        batch_op.drop_index('ix_external_references_system_external')
        batch_op.drop_index(batch_op.f('ix_external_references_item_id'))
        batch_op.drop_index(batch_op.f('ix_external_references_external_id'))

    op.drop_table('external_references')
    with op.batch_alter_table('partitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partitions_uuid'))
        batch_op.drop_index(batch_op.f('ix_partitions_slug'))
        batch_op.drop_index(batch_op.f('ix_partitions_artefact_id'))

    op.drop_table('partitions')

    # Drop the deferred circular FK before removing either of the two tables.
    op.drop_constraint('fk_artefacts_derived_from_analysis', 'artefacts', type_='foreignkey')

    # Drop analyses before artefacts: analyses.artefact_id references artefacts,
    # so artefacts cannot be dropped while analyses still exists.
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analyses_uuid'))
        batch_op.drop_index(batch_op.f('ix_analyses_slug'))
        batch_op.drop_index(batch_op.f('ix_analyses_artefact_id'))

    op.drop_table('analyses')
    with op.batch_alter_table('artefacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artefacts_uuid'))
        batch_op.drop_index(batch_op.f('ix_artefacts_slug'))
        batch_op.drop_index(batch_op.f('ix_artefacts_parent_artefact_id'))
        batch_op.drop_index(batch_op.f('ix_artefacts_item_id'))
        batch_op.drop_index(batch_op.f('ix_artefacts_derived_from_analysis_id'))

    op.drop_table('artefacts')
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_uuid'))
        batch_op.drop_index(batch_op.f('ix_items_slug'))
        batch_op.drop_index(batch_op.f('ix_items_platform_id'))
        batch_op.drop_index(batch_op.f('ix_items_name'))
        batch_op.drop_index(batch_op.f('ix_items_category_id'))

    op.drop_table('items')
    with op.batch_alter_table('hash_databases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hash_databases_name'))

    op.drop_table('hash_databases')
    op.drop_table('user')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_name'))

    op.drop_table('tags')
    with op.batch_alter_table('platforms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_platforms_name'))

    op.drop_table('platforms')
    with op.batch_alter_table('external_systems', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_external_systems_name'))

    op.drop_table('external_systems')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_name'))

    op.drop_table('categories')
    # ### end Alembic commands ###
